"""add phon number column into User table

Revision ID: 97556301faa1
Revises: 97c1b9c26801
Create Date: 2024-08-30 19:45:58.554134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97556301faa1'
down_revision: Union[str, None] = '97c1b9c26801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'phone_number')
    # ### end Alembic commands ###
