"""Auto-generating rest of the columns

Revision ID: 97c1b9c26801
Revises: 07cf7485b03f
Create Date: 2024-08-30 19:33:00.740441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97c1b9c26801'
down_revision: Union[str, None] = '07cf7485b03f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MyItems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_price', sa.Integer(), nullable=False),
    sa.Column('sale', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Vote',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['Posts.post_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.add_column('User', sa.Column('user_name', sa.String(), nullable=False))
    op.add_column('User', sa.Column('user_password', sa.String(), nullable=False))
    op.drop_column('User', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('User', 'user_password')
    op.drop_column('User', 'user_name')
    op.drop_table('Vote')
    op.drop_table('MyItems')
    # ### end Alembic commands ###
